docs/source/webservices.rst

This PR adds the missing documentation in the webservices.rst file.

Changes in the documentation file: webservices.rst

---

podaac/podaac.py

- This solves the [issue#5](https://github.com/lewismc/podaacpy/issues/5)

Updating the extract granule functionality in the podaac API

---

podaac/nose_tests_podaac/podaac_test.py

- This PR adds a test case to the extract_granule() fucntion in podaacpy API

Adding a test case to extract granule function in podaacpy API

---

podaac/podaac.py

- This PR incorporates the changes suggested @ https://podaac.jpl.nasa.gov/forum/viewforum.php?f=6
- This PR solves the issue #25

Changes in podaac.py this solves #25

---

podaac/nose_tests_podaac/podaac_test.py
podaac/podaac.py

- This PR adds test cases for the functions search_dataset() and search_granule() functions in podaac.py file. 
- This PR hopefully increases the code coverage.

Adding test cases to search_dataset() and search_granule() functions

---

.landscape.yml
setup.py

- Updated the requirements in setup.py file.
- Changed the indentation in .landscape.yml

Updating setup.py and .landscape.yml

---

podaac/podaac.py
podaac/tests/podaac_test.py

- Changes the image download format into png since it is returned as png image by the podaac web service.

Changing the image type from .jpg to .png

---

podaac/podaac_data_source.py
podaac/podaac_utils.py

- this PR removes unnecessary imports from both podaac_data_source and also podaac_utils. 
- I have once again verified if all dependencies are present in setup.py and running smoothly when we try 'python setup.py install', everything looks good.

Removing unnecessary imports

---

docs/source/quickstart.rst
podaac/podaac_data_source.py
podaac/podaac_utils.py
podaac/tests/podaac_test.py

- Made all the arguments lowercase, to make them PEP8 compliant.

Addressing landscape issues and PEP8 violations

---

.travis.yml

Revert "Automated PyPI deployments with Travis CI"

---

.travis.yml

This fixes https://github.com/lewismc/podaacpy/issues/55

Automated PyPI deployments with Travis CI

---

.travis.yml

- Add -v flag to nosetests
- Fix testpypi deploy steps
- Add pip cache step
- Disable email notification
This fixes https://github.com/lewismc/podaacpy/issues/62

Update Travis CI Build

---

podaac/podaac.py
podaac/podaac_utils.py
podaac/tests/podaac_test.py
setup.py

- This PR addresses all the changes needed to be addressed to update podaacpy.
- I have added the function datset_load_variables for now.
- I have also added tests for the same, these tests aren't final and will be updated upon thorough discussion.
- I will add to this PR until all the tests start passing again.

Updating podaacpy to include the changes of PO.DAAC v3.2.2

---

docs/source/introduction.rst
docs/source/quickstart.rst
docs/source/webservices.rst
podaac/podaac.py

- I have updated introduction.rst, quickstart.rst and webservices.rst
- Cleaned up the documentation in podaac
- Build ran successfully in local machine
this closes #67 
@lewismc

Updating the documentation

---

podaac/podaac.py
podaac/tests/podaac_test.py

- Updating all the test cases to improve code coverage.
this closes #71 
@lewismc

Updating all the tests cases

---

.travis.yml
README.rst
podaac/podaac.py
podaac/tests/podaac_test.py
setup.py

- Add python versions to .travis.yml
- Add python 2 and 3 badge to Readme
- Remove urllib and use future.moves.urllib in podaac.py and test
- Update requirements in setup.py
Fixes #75

Ensure that urllib permits use within Python 2.7

---

podaac/podaac.py

- After adding this to the documentation, it looks something like this

Adding possible status values returned by subset_status

---

podaac/tests/mcc_test.py

Updating test cases of metadata compliance checker

---

MANIFEST.in
setup.py

This issue is an attempt to address @agoodm comments over on #83 
Still missing is the MANIFEST.in file, @agoodm do you have ab example of what this looks like?

Add recipe to conda-forge

---

podaac/podaac.py

This fixes #87, and is a continuation of #88. See my posts in that PR for an explanation for the changes. Note that I also tested this in a clean environment with the latest ocw code and was able to pass all of the tests for that as well.

Fix extract_l4_granule

---

README.rst

Updating README to point to nasa/podaacpy

---

podaac/l2ss.py
podaac/tests/l2ss_tests.py

- Following python conventions to improve code health.
- Removing redundant exception handling in l2ss.py

Making changes according to python convention

---

podaac/l2ss.py
podaac/tests/l2ss_tests.py

- Some of the parameters were overlooked in l2ss, they have been addressed here. 
- I have also updated the documentation of dataset_search just to see whether the changes are being reflected here http://podaacpy.readthedocs.io/en/latest/l2ss.html
@lewismc

Updating the parameters of dataset_search function

---

podaac/l2ss.py
podaac/podaac.py

- Documentation has been added.
- I have also removed unnecessary imports from the code base.

Adding documnetation to l2ss

---

podaac/podaac.py

- Yet another improvement in documentation. :octocat:

Improving the documentation of granule_subset

---

README.rst
docs/source/introduction.rst
docs/source/oceancolor.rst
podaac/oceancolor.py
podaac/tests/oceancolor_test.py

ISSUE-114 Extend Podaacpy to OceanColor Data

---

podaac/tests/oceancolor_test.py

- Changed the assertion to Unicode from String.
- Added additional exception assert_raises to improve the coverage.

Updating the test case oceancolor_test.test_file_search

---

examples/README.rst

documentartion -> documentation

---

docs/source/quickstart.rst

Fix typo on paragraph #42

---

examples/Using podaacpy to interact with PO.DAAC Drive.ipynb
podaac/drive.py

This issue addresses #131 
CC @jelya

ISSUE-131 Maintain directory structure when downloading from PODAAC Drive

---

podaac/podaac.py

This PR is only an update to the dataset_variable function and does not include the complete solution to #128.

Updating dataset_variable to support L3 and L4 datasets

---

podaac/drive.py

An attempt to fix[Issue#135](https://github.com/nasa/podaacpy/issues/135). 
Thanks for testing it out.

ISSUE-#135 pull request

---

.deepsource.toml
podaac/drive.py
podaac/l2ss.py
podaac/oceancolor.py
podaac/podaac.py

Changes:
- In `podaac/drive.py` and `podaac/l2ss.py`, fix dangerous default argument (mutables) from being passed in methods
- In `podaac/oceancolor.py`, fix one instance where a mix of tabs and spaces was used
- Removed unused imports from `podaac/drive.py`
- Removed an instance of superfluous parenthesis from `podaac/podaac.py`
--- 
This PR also adds `.deepsource.toml` configuration file to run Continuous Quality analysis on the repo with [DeepSource](https://deepsource.io). Upon enabling DeepSource, quality analysis will be run on every PR to detect 500+ types of problems in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
DeepSource is a free to use for open-source projects, and is used by teams at Uber, Stripe, Slack among many others.
To enable …

Fix some bug risks and code quality issues

---

.travis.yml
podaac/drive.py
podaac/l2ss.py
podaac/mcc.py
podaac/oceancolor.py
podaac/podaac.py
podaac/podaac_utils.py
podaac/tests/l2ss_tests.py
podaac/tests/mcc_test.py
podaac/tests/oceancolor_test.py
podaac/tests/podaac_test.py
setup.py

ISSUE-140 Replace xml.etree.ElementTree.fromstring functions with the defusedxml equivalents
